spring:
  application:
    name: lynk
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/lynk}

lynk:
  snowflake:
    machine-id: ${LYNK_MACHINE_ID:0}
    epoch: "2025-01-01T00:00:00Z"
  url:
    default-expiry: 365d
